### ISSUE TITLE
Issues with nohup

### ISSUE THREAD

**Issue by fka21** [MetazoaPhylogenomicsLab/FANTASIA#4]
Hello @gmartinezredondo,

Thanks for developing this great tool! I am very excited to test it on my own species, but I ran into some difficulties while running it. I am using a local high-performance computer and installed FANTASIA with both singularity and also the precompiled version of it after standard installation steps. With both versions, I attempted to run it with nohup, but I different error messages. I might have misunderstood something with the running instructions, if so please correct me. 

Anyhow, here is the command used with the singularity version:
` nohup ./fantasia_sha256.06f759be1e48bf4f72aed0d4bb4fe2fd6e05774bb58131b131f0128c7b0efc84.sif --infile schMedA2_h1.pep --outpath ./ --prefix asmed &`

And the error message from the nohup file:
[nohup_singularity_version.txt](https://github.com/MetazoaPhylogenomicsLab/FANTASIA/files/14615237/nohup_singularity_version.txt)

For the precompiled version I used the commands: 
`../FANTASIA/generate_gopredsim_input_files.sh -i schMedA2_h1.pep  -p -x asmed -o /projects/ferenc.kagan/Tools/FANTASIA/sandbox/`
The above command finished without any errors (gopredsim conda environment was active while running).

After config file generation I used the following command:
` nohup ../FANTASIA/launch_gopredsim_pipeline.sh  -m prott5 -x asmed -o /projects/ferenc.kagan/Tools/FANTASIA/sandbox &`

And here is the error message from the nohup file:
[nohup_precompiled_version.txt](https://github.com/MetazoaPhylogenomicsLab/FANTASIA/files/14615245/nohup_precompiled_version.txt)

Any help is very welcome!

Cheers,
Ferenc

**Comment by gmartinezredondo** [comment]
Hi, Ferenc!
I'm not sure about the error with the singularity. It is not able to find your file. I've just tested it on my computer with nohup (I hadn't tried it before) and it works. I will run some tests to see if I can reproduce your error and find a solution.
The second error is my fault. The version you probably have contains an old version of the script with some lines specific for loading libraries in my cluster. I uploaded a fixed version one or two days ago. Sorry for that.

**Comment by gmartinezredondo** [comment]
When you execute the singularity version, are there any output files in your home directory? I've been told of an issue related to this that gives the same error you get.

**Comment by fka21** [comment]
Hi and thanks for the reply. 

I have downloaded the most recent singularity image I think (it was uploaded March 13th) using the link in the git (https://cloud.sylabs.io/library/gemma.martinezredondo/fantasia/fantasia). The same is true for the precompiled version. I installed these versions on March 14th if that matters.

Interestingly, yes, there are output files in the home directory. Should I then run the pipeline from the home directory?

Cheers,
Ferenc

**Comment by gmartinezredondo** [comment]
Try running the singularity from the home directory, yes. I'm trying to discover why this is happening and how to fix it.

About the precompiled version, I believe that in lines 14 and 15 in the `launch_gopredsim_pipeline.sh` script it says something like `module load XXX`. This has to be deleted. I will change this in the gzip.

**Comment by fka21** [comment]
I tried running from the home directory and I am still facing the same issue. It is generating an empty `config_files` directory with `embeddings` and `gopredsim` subdirectories. Additionally, now I am testing to run it with `screen` and it is working so far.
