### ISSUE TITLE
Singularity definition file

### ISSUE THREAD

**Issue by lecorguille** [MetazoaPhylogenomicsLab/FANTASIA#5]
Hi,
On our infrastructures, we choosed to switch to Apptainer and since we can't access to the Sylabs library of images anymore.

Can you share your Singularity defination file with me ?

Thanks

**Comment by gmartinezredondo** [comment]
Hi!

Sure, I can share it with you. Could you give me your email address?

Gemma

**Comment by lecorguille** [comment]
lecorguille 📧 sb-roscoff.fr

**Comment by abretaud** [comment]
Would it be possible to upload this definition file on this github repo? Also I'm surprised that the code is not available on this repo, but only gofile.me!? Wouldn't it be possible to deposit it on github with a proper license? It would make packaging much much easier

**Comment by gmartinezredondo** [comment]
The definition file has been uploaded to the repo.

The code was not directly uploaded on the repo because one of the files required to run it exceeds the size upload limit in GitHub. We will explore new options when we start working on future versions.
