### ISSUE TITLE
Clarification on reliability filtering in FANTASIA Pipeline

### ISSUE THREAD

**Issue by lcanoalmarza** [MetazoaPhylogenomicsLab/FANTASIA#7]
Hello [@gmartinezredondo](https://github.com/gmartinezredondo),

I have a question regarding the reliability threshold implementation described in Martínez-Redondo, Barrios-Núñez, et al. (2024). In the methods section, it is stated that a reliability index was established for each non-homology-based model with thresholds derived from CAFA3 evaluations. However, later in the text, it mentions that this filter was only applied during the initial analyses. Could you please clarify whether any reliability filtering is currently implemented within the FANTASIA pipeline?

Thank you in advance for your help.

Laura Cano

**Comment by gmartinezredondo** [comment]
Hello, Laura:

The FANTASIA pipeline does not implement this filtering in its current version. But, the raw results can be found in a folder called "prefix_you_used_prott5" that is created when running the pipeline. Here, you can find the information on the reliability index if you want to perform this filtering for any analysis.

Hope this answers your question.

Best,

Gemma

**Comment by lcanoalmarza** [comment]
Thank you so much for the clarification, Gemma. 

Best, 

Laura
